"use server";
import {prisma} from "@/lib/prisma"; import {getSession} from "@/lib/auth"; import {redirect} from "next/navigation"; import bcrypt from "bcryptjs";
async function guard(){const s=await getSession();if(!s||(s.role!=="admin"&&s.role!=="master"))redirect("/login");return s}
const n=(v:any)=>Number(v||0);
export async function createAnggota(fd:FormData){await guard();const nomor=String(fd.get("nomor")||"").trim();if(!nomor)throw new Error("Nomor anggota wajib diisi");const exists=await prisma.anggota.findFirst({where:{nomorAnggota:nomor}});if(exists)throw new Error("Nomor anggota sudah digunakan");const password=String(fd.get("password")||nomor);await prisma.anggota.create({data:{nomorAnggota:nomor,nama:String(fd.get("nama")||""),koperasiUser:String(fd.get("koperasi")||""),usernameUser:String(fd.get("username")||nomor),passwordUser:await bcrypt.hash(password,12),nik:String(fd.get("nik")||""),jabatanAnggota:String(fd.get("jabatan")||""),unit:String(fd.get("unit")||""),alamat:String(fd.get("alamat")||""),email:String(fd.get("email")||""),nomorTelepon:String(fd.get("telepon")||""),tempatLahir:String(fd.get("tempatLahir")||""),tanggalLahir:fd.get("tanggalLahir")?new Date(String(fd.get("tanggalLahir"))):null,jenisKelamin:String(fd.get("jenisKelamin")||""),statusAnggota:String(fd.get("status")||"Aktif")}});redirect("/admin/anggota")}
export async function deleteAnggota(fd:FormData){await guard();await prisma.anggota.delete({where:{id:n(fd.get("id"))}});redirect("/admin/anggota")}
export async function createSimpanan(fd:FormData){await guard();const nomor=String(fd.get("nomor")||"");const a=await prisma.anggota.findFirst({where:{nomorAnggota:nomor}});if(!a)throw new Error("Anggota tidak ditemukan");const vals={pokok:n(fd.get("pokok")),wajib:n(fd.get("wajib")),sukarela:n(fd.get("sukarela")),hariraya:n(fd.get("hariraya")),khusus:n(fd.get("khusus"))};const old=await prisma.simpanan.findFirst({where:{nomorAnggota:nomor}});await prisma.$transaction(async tx=>{if(old)await tx.simpanan.update({where:{idSmp:old.idSmp},data:{spokok:{increment:vals.pokok},swajib:{increment:vals.wajib},ssukarela:{increment:vals.sukarela},shariraya:{increment:vals.hariraya},skhusus:{increment:vals.khusus}}});else await tx.simpanan.create({data:{nomorAnggota:nomor,namaAnggota:a.nama,unit:a.unit,spokok:vals.pokok,swajib:vals.wajib,ssukarela:vals.sukarela,shariraya:vals.hariraya,skhusus:vals.khusus}});await tx.simpananRecord.create({data:{idAnggota:nomor,pokokRec:vals.pokok,wajibRec:vals.wajib,sukarelaRec:vals.sukarela,harirayaRec:vals.hariraya,khususRec:vals.khusus,tglSimpanan:new Date(),bulan:String(new Date().getMonth()+1).padStart(2,"0")}})});redirect("/admin/simpanan")}
export async function createPinjaman(fd:FormData){await guard();const nomor=String(fd.get("nomor")||"");const a=await prisma.anggota.findFirst({where:{nomorAnggota:nomor}});if(!a)throw new Error("Anggota tidak ditemukan");const v={pokok:n(fd.get("pokok")),jasa:n(fd.get("jasa")),khususPokok:n(fd.get("khususPokok")),khususJasa:n(fd.get("khususJasa")),angsuranPokok:n(fd.get("angsuranPokok")),angsuranJasa:n(fd.get("angsuranJasa"))};const old=await prisma.pinjaman.findFirst({where:{nomorAnggota:nomor}});await prisma.$transaction(async tx=>{if(old)await tx.pinjaman.update({where:{idPinjaman:old.idPinjaman},data:{pinjamanPokok:{increment:v.pokok},pinjamanJasa:{increment:v.jasa},pinjamanKhususPokok:{increment:v.khususPokok},pinjamanKhususJasa:{increment:v.khususJasa},angsuranPokok:{increment:v.angsuranPokok},angsuranJasa:{increment:v.angsuranJasa}}});else await tx.pinjaman.create({data:{nomorAnggota:nomor,namaAnggota:a.nama||"",unit:a.unit,pinjamanPokok:v.pokok,pinjamanJasa:v.jasa,pinjamanKhususPokok:v.khususPokok,pinjamanKhususJasa:v.khususJasa,angsuranPokok:v.angsuranPokok,angsuranJasa:v.angsuranJasa}});await tx.pinjamanRecord.create({data:{idAnggota:nomor,pinjamanPokokRec:v.pokok,pinjamanJasaRec:v.jasa,pinjamanKhususPokok:v.khususPokok,pinjamanKhususJasa:v.khususJasa,angsuranPokok:v.angsuranPokok,angsuranJasa:v.angsuranJasa,tanggalPinjaman:new Date(),bulan:String(new Date().getMonth()+1).padStart(2,"0")}})});redirect("/admin/pinjaman")}
export async function deleteSimpanan(fd:FormData){await guard();await prisma.simpanan.delete({where:{idSmp:n(fd.get("id"))}});redirect("/admin/simpanan")}
export async function deletePinjaman(fd:FormData){await guard();await prisma.pinjaman.delete({where:{idPinjaman:n(fd.get("id"))}});redirect("/admin/pinjaman")}
