import Link from "next/link";
import {prisma} from "@/lib/prisma";import {getSession} from "@/lib/auth";import {redirect} from "next/navigation";
import {createBank,deleteBank,createBeban,deleteBeban,createAset,deleteAset,createEkuitas,deleteEkuitas,createKewajiban,deleteKewajiban,createShu,deleteShu} from "./actions";
const rp=(v:number)=>`Rp ${v.toLocaleString("id-ID")}`;
const total=(xs:any[],keys:string[])=>xs.reduce((s,x)=>s+keys.reduce((a,k)=>a+Number(x[k]||0),0),0);
export default async function Page(){const s=await getSession();if(!s||(s.role!=="admin"&&s.role!=="master"))redirect("/login");
const [bank,beban,aset,ekuitas,kew,shu]=await Promise.all([prisma.bankRecord.findMany({orderBy:{idBankRec:"desc"},take:30}),prisma.beban.findMany({orderBy:{idBeban:"desc"},take:20}),prisma.asetTetap.findMany({orderBy:{idAsetTetap:"desc"},take:20}),prisma.ekuitas.findMany({orderBy:{tahun:"desc"},take:20}),prisma.kewajiban.findMany({orderBy:{idKewajiban:"desc"},take:20}),prisma.shu.findMany({orderBy:{tahun:"desc"},take:20})]);
const kas=total(bank,["uangMasuk"])-total(bank,["uangKeluar"]);const bebanTotal=total(beban,["administrasi","rapatAnggota","insentif","honorKetuaKel","thr","atk","transportasi","sisihGedung","sisihPiutang","susutInventaris","konsumsi","rawatAset","bebanLain","pajakBadan"]);const asetNet=total(aset,["inventaris"])-total(aset,["penyusutan"]);const eq=total(ekuitas,["hibah","modal","resiko"]);const kw=total(kew,["sewaGedung","utangPajak","danaPengurusPengawas","danaPendidikan","danaKaryawan","danaSosial"]);
return <main className="page"><div className="top"><div><span className="eyebrow">KEUANGAN KOPERASI</span><h1>Keuangan</h1><p>Kelola kas/bank, beban, aset tetap, ekuitas, kewajiban, dan SHU.</p></div><Link className="btn" href="/admin/laporan">Laporan →</Link></div>
<div className="stats"><div className="stat"><small>Kas / Bank bersih</small><strong>{rp(kas)}</strong></div><div className="stat"><small>Aset tetap bersih</small><strong>{rp(asetNet)}</strong></div><div className="stat"><small>Ekuitas</small><strong>{rp(eq)}</strong></div></div>
<section className="card form-card"><div className="top"><div><h2>Kas / Bank</h2><p>Catat uang masuk dan keluar.</p></div></div><form action={createBank} className="form-grid"><label>Uang masuk<input name="masuk" type="number" min="0" defaultValue="0"/></label><label>Uang keluar<input name="keluar" type="number" min="0" defaultValue="0"/></label><label>Tanggal<input name="tanggal" type="date" required/></label><label className="full">Keterangan<input name="keterangan" required placeholder="Contoh: Setoran kas"/></label><button className="btn">Simpan transaksi</button></form><div className="table-wrap"><table><thead><tr><th>Tanggal</th><th>Keterangan</th><th>Masuk</th><th>Keluar</th><th>Aksi</th></tr></thead><tbody>{bank.map(x=><tr key={x.idBankRec}><td>{x.tanggal.toLocaleDateString("id-ID")}</td><td>{x.keterangan}</td><td>{rp(Number(x.uangMasuk))}</td><td>{rp(Number(x.uangKeluar))}</td><td><form action={deleteBank}><input type="hidden" name="id" value={x.idBankRec}/><button className="danger">Hapus</button></form></td></tr>)}</tbody></table></div></section>
<section className="card form-card"><div className="top"><div><h2>Beban</h2><p>Total beban tercatat: <b>{rp(bebanTotal)}</b></p></div></div><form action={createBeban} className="form-grid">{[["administrasi","Administrasi"],["pendapatanLain","Pendapatan lain"],["rapatAnggota","Rapat anggota"],["insentif","Insentif"],["honorKetuaKel","Honor ketua"],["thr","THR"],["atk","ATK"],["transportasi","Transportasi"],["sisihGedung","Sisih gedung"],["sisihPiutang","Sisih piutang"],["susutInventaris","Susut inventaris"],["konsumsi","Konsumsi"],["rawatAset","Rawat aset"],["bebanLain","Beban lain"],["pajakBadan","Pajak badan"]].map(([n,l])=><label key={n}>{l}<input name={n} type="number" min="0" defaultValue="0"/></label>)}<label>Tahun<input name="tahun" type="date" required/></label><button className="btn">Simpan beban</button></form></section>
<section className="grid"><div className="card"><h2>Aset Tetap</h2><form action={createAset} className="form-grid"><label>Inventaris<input name="inventaris" type="number" min="0" required/></label><label>Penyusutan<input name="penyusutan" type="number" min="0" required/></label><label>Tahun<input name="tahun" type="date" required/></label><button className="btn">Tambah aset</button></form><div className="table-wrap"><table><thead><tr><th>Tahun</th><th>Inventaris</th><th>Penyusutan</th><th>Aksi</th></tr></thead><tbody>{aset.map(x=><tr key={x.idAsetTetap}><td>{x.tahun.getFullYear()}</td><td>{rp(Number(x.inventaris))}</td><td>{rp(Number(x.penyusutan))}</td><td><form action={deleteAset}><input type="hidden" name="id" value={x.idAsetTetap}/><button className="danger">Hapus</button></form></td></tr>)}</tbody></table></div></div>
<div className="card"><h2>Ekuitas</h2><form action={createEkuitas} className="form-grid"><label>Hibah<input name="hibah" type="number" defaultValue="0"/></label><label>Modal<input name="modal" type="number" defaultValue="0"/></label><label>Resiko<input name="resiko" type="number" defaultValue="0"/></label><label>Tahun<input name="tahun" type="number" required/></label><button className="btn">Simpan ekuitas</button></form><div className="table-wrap"><table><thead><tr><th>Tahun</th><th>Nilai</th><th>Aksi</th></tr></thead><tbody>{ekuitas.map(x=><tr key={x.idEkuitas}><td>{x.tahun}</td><td>{rp(Number(x.hibah||0)+Number(x.modal||0)+Number(x.resiko||0))}</td><td><form action={deleteEkuitas}><input type="hidden" name="id" value={x.idEkuitas}/><button className="danger">Hapus</button></form></td></tr>)}</tbody></table></div></div></section>
<section className="grid"><div className="card"><h2>Kewajiban</h2><form action={createKewajiban} className="form-grid"><label>Sewa gedung<input name="sewa" type="number" defaultValue="0"/></label><label>Utang pajak<input name="pajak" type="number" defaultValue="0"/></label><label>Dana pengurus/pengawas<input name="pengurus" type="number" defaultValue="0"/></label><label>Dana pendidikan<input name="pendidikan" type="number" defaultValue="0"/></label><label>Dana karyawan<input name="karyawan" type="number" defaultValue="0"/></label><label>Dana sosial<input name="sosial" type="number" defaultValue="0"/></label><label>Tanggal<input name="tanggal" type="date" required/></label><button className="btn">Simpan kewajiban</button></form></div>
<div className="card"><h2>SHU</h2><form action={createShu} className="form-grid">{[["cadanganModal","Cadangan modal"],["cadanganResiko","Cadangan resiko"],["anggotaSimpanan","Bagian anggota simpanan"],["anggotaPinjaman","Bagian anggota pinjaman"],["danaPp","Dana PP"],["danaPendidikan","Dana pendidikan"],["danaKaryawan","Dana karyawan"],["danaSosial","Dana sosial"]].map(([n,l])=><label key={n}>{l}<input name={n} type="number" defaultValue="0"/></label>)}<label>Tahun<input name="tahun" type="number" required/></label><button className="btn">Simpan SHU</button></form></div></section>
<section className="card"><div className="top"><div><h2>Ringkasan kewajiban & SHU</h2><p>Kewajiban tercatat: <b>{rp(kw)}</b>. Data SHU: {shu.length} periode.</p></div></div><div className="table-wrap"><table><thead><tr><th>Tahun</th><th>Cadangan modal</th><th>Anggota simpanan</th><th>Dana sosial</th><th>Aksi</th></tr></thead><tbody>{shu.map(x=><tr key={x.idShu}><td>{x.tahun}</td><td>{rp(x.cadanganModal)}</td><td>{rp(x.anggotaSimpanan)}</td><td>{rp(x.danaSosial)}</td><td><form action={deleteShu}><input type="hidden" name="id" value={x.idShu}/><button className="danger">Hapus</button></form></td></tr>)}</tbody></table></div></section>
</main>}