import Link from "next/link";
import {prisma} from "@/lib/prisma";import {getSession} from "@/lib/auth";import {redirect} from "next/navigation";
const rp=(v:number)=>`Rp ${Math.round(v).toLocaleString("id-ID")}`;
const sum=(xs:any[],keys:string[])=>xs.reduce((s,x)=>s+keys.reduce((a,k)=>a+Number(x[k]||0),0),0);
export default async function Page({searchParams}:{searchParams:Promise<{tahun?:string}>}){const s=await getSession();if(!s||(s.role!=="admin"&&s.role!=="master"))redirect("/login");const q=await searchParams;const tahun=Number(q.tahun)||new Date().getFullYear();const from=new Date(tahun,0,1);const to=new Date(tahun+1,0,1);
const [sim,pin,bank,beban,aset,eku,kew,shu]=await Promise.all([
 prisma.simpanan.findMany(),prisma.pinjaman.findMany(),prisma.bankRecord.findMany({where:{tanggal:{gte:from,lt:to}}}),prisma.beban.findMany({where:{tahun:{gte:from,lt:to}}}),prisma.asetTetap.findMany({where:{tahun:{gte:from,lt:to}}}),prisma.ekuitas.findMany({where:{tahun}}),prisma.kewajiban.findMany({where:{OR:[{tanggalKewajiban:null},{tanggalKewajiban:{gte:from,lt:to}}]}}),prisma.shu.findMany({where:{tahun}})]);
const simpanan=sum(sim,["spokok","swajib","ssukarela","shariraya","skhusus"]);const pinjaman=sum(pin,["pinjamanPokok","pinjamanKhususPokok"]);const masuk=sum(bank,["uangMasuk"]);const keluar=sum(bank,["uangKeluar"]);const bebanTotal=sum(beban,["administrasi","rapatAnggota","insentif","honorKetuaKel","thr","atk","transportasi","sisihGedung","sisihPiutang","susutInventaris","konsumsi","rawatAset","bebanLain","pajakBadan"]);const asetBruto=sum(aset,["inventaris"]);const penyusutan=sum(aset,["penyusutan"]);const asetBersih=asetBruto-penyusutan;const ekuitas=sum(eku,["hibah","modal","resiko"]);const kewajiban=sum(kew,["sewaGedung","utangPajak","danaPengurusPengawas","danaPendidikan","danaKaryawan","danaSosial"]);const kas=masuk-keluar;const surplus=masuk-bebanTotal;
return <main className="page"><div className="top"><div><span className="eyebrow">LAPORAN KEUANGAN</span><h1>Laporan & Neraca</h1><p>Periode laporan tahun {tahun}. Nilai dihitung dari transaksi yang tersimpan.</p></div><div style={{display:"flex",gap:10}}><Link className="btn" href="/admin/keuangan">Keuangan</Link><Link className="btn" href="/admin">Dashboard</Link></div></div>
<section className="card form-card"><form className="form-grid" method="get"><label>Tahun laporan<input name="tahun" type="number" min="2000" max="2100" defaultValue={tahun}/></label><button className="btn">Tampilkan</button></form></section>
<div className="stats"><div className="stat"><small>Kas / Bank bersih</small><strong>{rp(kas)}</strong></div><div className="stat"><small>Total simpanan</small><strong>{rp(simpanan)}</strong></div><div className="stat"><small>Total pinjaman</small><strong>{rp(pinjaman)}</strong></div></div>
<section className="grid"><div className="card"><h2>Neraca — Aset</h2><p>Kas / Bank <b>{rp(kas)}</b></p><p>Piutang / Pinjaman <b>{rp(pinjaman)}</b></p><p>Aset tetap bruto <b>{rp(asetBruto)}</b></p><p>Akumulasi penyusutan <b>({rp(penyusutan)})</b></p><hr/><p><b>Total aset bersih {rp(kas+pinjaman+asetBersih)}</b></p></div>
<div className="card"><h2>Neraca — Kewajiban & Ekuitas</h2><p>Total kewajiban <b>{rp(kewajiban)}</b></p><p>Total ekuitas <b>{rp(ekuitas)}</b></p><hr/><p><b>Kewajiban + ekuitas {rp(kewajiban+ekuitas)}</b></p><p className="muted">Sumber nilai mengikuti data yang tersedia pada periode terpilih.</p></div></section>
<section className="card"><h2>Arus kas & hasil periode</h2><div className="master-overview"><div><small>Uang masuk</small><strong>{rp(masuk)}</strong><span>transaksi bank</span></div><div><small>Uang keluar</small><strong>{rp(keluar)}</strong><span>transaksi bank</span></div><div><small>Beban</small><strong>{rp(bebanTotal)}</strong><span>beban tercatat</span></div></div><p style={{marginTop:18}}>Surplus sederhana berdasarkan kas masuk dikurangi beban: <b>{rp(surplus)}</b>. Angka ini adalah ringkasan operasional, bukan pengganti laporan akuntansi resmi.</p></section>
<section className="card"><div className="top"><div><h2>SHU {tahun}</h2><p>{shu.length} pencatatan periode.</p></div></div><div className="table-wrap"><table><thead><tr><th>Cadangan modal</th><th>Cadangan resiko</th><th>Anggota simpanan</th><th>Anggota pinjaman</th><th>Dana PP</th><th>Pendidikan</th><th>Karyawan</th><th>Sosial</th></tr></thead><tbody>{shu.map(x=><tr key={x.idShu}><td>{rp(x.cadanganModal)}</td><td>{rp(x.cadanganResiko)}</td><td>{rp(x.anggotaSimpanan)}</td><td>{rp(x.anggotaPinjaman)}</td><td>{rp(x.danaPp)}</td><td>{rp(x.danaPendidikan)}</td><td>{rp(x.danaKaryawan)}</td><td>{rp(x.danaSosial)}</td></tr>)}{!shu.length&&<tr><td colSpan={8}>Belum ada data SHU untuk tahun {tahun}.</td></tr>}</tbody></table></div></section></main>}